# Libreria Numpy

In [1]:
import numpy as np

## Creando Arrays

In [10]:
A=np.arange(1,101,1)
print(A)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


Filtrando Elementos de un Array

In [5]:
A=np.array([[1,7,3,4],[2,12,4,1],[2,9,7,8]])
print(A)
A[A%2==0 | (A%3==0)]

[[ 1  7  3  4]
 [ 2 12  4  1]
 [ 2  9  7  8]]


array([3, 4, 2, 4, 2, 9, 8])

In [7]:
f1=[1,2,3,4]
M=np.array([f1,[3*k for k in f1],[(3*k)**2 for k in f1]])
print(M)
print('El numero de elementos impares es: ',M[M%2!=0].size)

[[  1   2   3   4]
 [  3   6   9  12]
 [  9  36  81 144]]
El numero de elementos impares es:  6


In [17]:
E=np.linspace(1,36,36)
E.reshape(6,6)

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36.]])